In [7]:
#Program scrapes NBA Player 2022-2023 Season Stats from stats.nba.com and creates a DataFrame with pandas

import pandas as pd
import requests

url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2022-23&SeasonSegment=&SeasonType=Regular%20Season&ShotClockRange=&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight='

headers = {
    'User-Agent': 'Mozilla/5.0',
    'x-nba-stats-origin': 'stats',
    'x-nba-stats-token': 'true',
    'Referer': 'https://stats.nba.com',
    'Connection': 'keep-alive',
    'Pragma': 'no-cache',
    'Cache-Control': 'no-cache',
    'Host': 'stats.nba.com'
}

response = requests.get(url, headers=headers).json()
header = response['resultSets'][0]['headers']
player_stats = response['resultSets'][0]['rowSet']
df = pd.DataFrame(player_stats, columns=header)
df

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,CFID,CFPARAMS
0,1630639,A.J. Lawson,A.J.,1610612742,DAL,22.0,2,2,0,1.000,...,444,465,461,457,477,191,22,477,5,"1630639,1610612742"
1,1631260,AJ Green,AJ,1610612749,MIL,23.0,14,12,2,0.857,...,369,461,362,313,415,191,22,398,5,"1631260,1610612749"
2,1631100,AJ Griffin,AJ,1610612737,ATL,19.0,32,13,19,0.406,...,340,376,155,297,220,191,22,209,5,"1631100,1610612737"
3,203932,Aaron Gordon,Aaron,1610612743,DEN,27.0,30,21,9,0.700,...,227,55,72,13,78,60,22,82,5,"203932,1610612743"
4,1628988,Aaron Holiday,Aaron,1610612737,ATL,26.0,32,17,15,0.531,...,241,289,326,207,330,191,22,331,5,"1628988,1610612737"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,1628380,Zach Collins,Zach,1610612759,SAS,25.0,25,11,14,0.440,...,5,115,193,447,175,191,22,171,5,"1628380,1610612759"
485,203897,Zach LaVine,Zach,1610612741,CHI,27.0,32,15,17,0.469,...,126,90,28,363,51,191,22,43,5,"203897,1610612741"
486,1630192,Zeke Nnaji,Zeke,1610612743,DEN,21.0,25,15,10,0.600,...,263,315,361,397,399,191,22,399,5,"1630192,1610612743"
487,1630533,Ziaire Williams,Ziaire,1610612763,MEM,21.0,10,6,4,0.600,...,174,306,340,438,326,191,22,321,5,"1630533,1610612763"
488,1629627,Zion Williamson,Zion,1610612740,NOP,22.0,28,17,11,0.607,...,124,8,19,22,20,60,22,25,5,"1629627,1610612740"